lang: ru-RU
encoding: utf-8

title: "legalchik"
description: "Coder from Kazan, Russia"

author: "legalchik"
url: https://legalchik.github.io

permalink: pretty
highlighter: rouge

sass:
  style: :compressed
